version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    expose:
      - "4567"
    environment:
      - DOCKER_HOST_IP
    links:
      - db
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    ports:
      - "8000:8000"
    expose:
      - "8000"